# Generated by Django 6.0 on 2025-12-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_doctor_remove_user_blood_group_user_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Cancelled by Patient', 'Cancelled by Patient'), ('No Show', 'No Show'), ('Pending Payment', 'Pending Payment'), ('Rejected', 'Rejected')], default='Scheduled', max_length=50),
        ),
    ]
