# Generated by Django 6.0 on 2026-01-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_blood_group_user_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
    ]
